### ISSUE TITLE
handshake alert: unrecognized name

### ISSUE THREAD

**Issue by astjohn** [onesky/i18n-one_sky-ruby#7]
When trying to upload yaml files using Jruby 1.7.2, I receive the following error. Any help is greatly appreciated.

```
$ bundle exec rake one_sky:upload --trace

** Invoke one_sky:upload (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute one_sky:upload
Uploading strings:
  count: 743
rake aborted!
handshake alert:  unrecognized_name
org/jruby/ext/openssl/SSLSocket.java:170:in `connect'
/home/adam/.rvm/rubies/jruby-1.7.2/lib/ruby/1.9/net/http.rb:799:in `connect'
org/jruby/ext/timeout/Timeout.java:105:in `timeout'
/home/adam/.rvm/rubies/jruby-1.7.2/lib/ruby/1.9/net/http.rb:799:in `connect'
/home/adam/.rvm/rubies/jruby-1.7.2/lib/ruby/1.9/net/http.rb:755:in `do_start'
/home/adam/.rvm/rubies/jruby-1.7.2/lib/ruby/1.9/net/http.rb:744:in `start'
/home/adam/.rvm/gems/jruby-1.7.2/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
/home/adam/.rvm/gems/jruby-1.7.2/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
/home/adam/.rvm/gems/jruby-1.7.2/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
/home/adam/.rvm/gems/jruby-1.7.2/gems/rest-client-1.6.7/lib/restclient.rb:72:in `post'
/home/adam/.rvm/gems/jruby-1.7.2/gems/one_sky-2.0.1/lib/one_sky/client.rb:59:in `fetch_response'
/home/adam/.rvm/gems/jruby-1.7.2/gems/one_sky-2.0.1/lib/one_sky/client.rb:29:in `post'
/home/adam/.rvm/gems/jruby-1.7.2/gems/one_sky-2.0.1/lib/one_sky/translation.rb:104:in `post'
/home/adam/.rvm/gems/jruby-1.7.2/gems/one_sky-2.0.1/lib/one_sky/translation.rb:21:in `input_strings'
/home/adam/.rvm/gems/jruby-1.7.2/gems/one_sky-2.0.1/lib/one_sky/translation.rb:36:in `input_phrases'
/home/adam/.rvm/gems/jruby-1.7.2/gems/i18n-one_sky-2.0.10/lib/i18n/one_sky/client_base.rb:116:in `upload_phrases'
/home/adam/.rvm/gems/jruby-1.7.2/gems/i18n-one_sky-2.0.10/lib/i18n/one_sky/simple_client.rb:48:in `upload'
/home/adam/.rvm/gems/jruby-1.7.2/gems/i18n-one_sky-2.0.10/lib/i18n/one_sky/rails/tasks/i18n-one_sky.rake:5:in `(root)'
org/jruby/RubyProc.java:249:in `call'
/home/adam/.rvm/gems/jruby-1.7.2/gems/rake-10.0.4/lib/rake/task.rb:246:in `execute'
org/jruby/RubyArray.java:1613:in `each'
/home/adam/.rvm/gems/jruby-1.7.2/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/home/adam/.rvm/gems/jruby-1.7.2/gems/rake-10.0.4/lib/rake/task.rb:184:in `invoke_with_call_chain'
/home/adam/.rvm/rubies/jruby-1.7.2/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/home/adam/.rvm/gems/jruby-1.7.2/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/home/adam/.rvm/gems/jruby-1.7.2/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/home/adam/.rvm/gems/jruby-1.7.2/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/home/adam/.rvm/gems/jruby-1.7.2/gems/rake-10.0.4/lib/rake/application.rb:101:in `top_level'
org/jruby/RubyArray.java:1613:in `each'
/home/adam/.rvm/gems/jruby-1.7.2/gems/rake-10.0.4/lib/rake/application.rb:101:in `top_level'
/home/adam/.rvm/gems/jruby-1.7.2/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/home/adam/.rvm/gems/jruby-1.7.2/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/home/adam/.rvm/gems/jruby-1.7.2/gems/rake-10.0.4/lib/rake/application.rb:73:in `run'
/home/adam/.rvm/gems/jruby-1.7.2/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/home/adam/.rvm/gems/jruby-1.7.2/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/home/adam/.rvm/gems/jruby-1.7.2/gems/rake-10.0.4/bin/rake:33:in `(root)'
org/jruby/RubyKernel.java:1046:in `load'
/home/adam/.rvm/gems/jruby-1.7.2/bin/rake:1:in `(root)'
org/jruby/RubyKernel.java:1066:in `eval'
/home/adam/.rvm/gems/jruby-1.7.2/bin/ruby_noexec_wrapper:14:in `(root)'
Tasks: TOP => one_sky:upload
```

**Comment by matthewrudy** [comment]
I think this may be a problem with SSL on the api.

``` bash
curl "https://api.oneskyapp.com/2" -v                                     ⏎
* About to connect() to api.oneskyapp.com port 443 (#0)
*   Trying 184.73.216.246...
* connected
* Connected to api.oneskyapp.com (184.73.216.246) port 443 (#0)
* SSLv3, TLS handshake, Client hello (1):
* error:14077458:SSL routines:SSL23_GET_SERVER_HELLO:reason(1112)
* Closing connection #0
curl: (35) error:14077458:SSL routines:SSL23_GET_SERVER_HELLO:reason(1112)
```

**Comment by matthewrudy** [comment]
this seems to be working ok now.
does it work for you @astjohn?

**Comment by kwunlokng** [comment]
Thanks @matthewrudy. 

@astjohn We found that 2 of our servers were very busy last week that causing invalid SSL connection. We have setup few more servers for temporarily solving this issue and is now double checking the servers to see if anything strange there. 

Please let me know if you are still experiencing the problem.

**Comment by astjohn** [comment]
Sorry for the late reply, but I had to put off i18n for a while. I just tried again with the same result. I'm using jruby 1.7.4. Same `handshake alert: unrecognised name` error.

When running curl as above, I get the following:

```
* About to connect() to api.oneskyapp.com port 443 (#0)
*   Trying 184.73.216.246... connected
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using DHE-RSA-AES256-SHA
* Server certificate:
*    subject: serialNumber=E/xQt3k6hDLxPuEY72QK9BDaKuBAntnw; OU=GT35753523; OU=See www.rapidssl.com/resources/cps (c)12; OU=Domain Control Validated - RapidSSL(R); CN=*.oneskyapp.com
*    start date: 2012-12-01 06:56:47 GMT
*    expire date: 2014-02-02 10:06:10 GMT
*    subjectAltName: api.oneskyapp.com matched
*    issuer: C=US; O=GeoTrust, Inc.; CN=RapidSSL CA
*    SSL certificate verify ok.
> GET /2 HTTP/1.1
> User-Agent: curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
> Host: api.oneskyapp.com
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Date: Wed, 24 Jul 2013 19:57:34 GMT
< Server: Apache
< Vary: Accept-Encoding
< Content-Length: 44
< Content-Type: text/html
< 
* Connection #0 to host api.oneskyapp.com left intact
* Closing connection #0
* SSLv3, TLS alert, Client hello (1):
{"response":"error","error":"API not found"}
```
